import { gql } from "@apollo/client";

export const getCommentByIdQuery = gql(`
query getCommentById($payload:getCommentByIdInput){
    getCommentById(payload:$payload){
        id
        comment
        mediaArray
        tweetId
        userId
        parentId
        savedPost{
            id
            commentId
        }
        repostComment{
            userId
            tweetId
            id
            commentId
         }
        tweet{
            id
            
        }
        likes{
            id
            userId
        }
        user{
            id
            firstName
            lastName
            userName
            email
            profileImgUrl
        }
        replies{
                id
                comment
                mediaArray
                savedPost{
                    tweetId
                    id
                    commentId
                }
                replies{
                id
                comment
                mediaArray
                likes{
                 id
                 userId
                 }
                 parent{
            id
            comment
            mediaArray
            user{
                id
                    firstName
                    lastName
                    userName
                    email
                    profileImgUrl
            }
            parent{
                id
                comment
                mediaArray
                user{
                    id
                    firstName
                    lastName
                    userName
                    email
                    profileImgUrl
                }
            }
          
        }

                user{
                    id
                    firstName
                    lastName
                    userName
                    email
                    profileImgUrl
                }
            }
                likes{
                 id
                 userId
                 }
                 parent{
            id
            comment
            mediaArray
            user{
                id
                    firstName
                    lastName
                    userName
                    email
                    profileImgUrl
            }
            parent{
                id
                comment
                mediaArray
                user{
                    id
                    firstName
                    lastName
                    userName
                    email
                    profileImgUrl
                }
            }
          
        }

                user{
                    id
                    firstName
                    lastName
                    userName
                    email
                    profileImgUrl
                }
            }
        parent{
            id
            comment
            mediaArray
            user{
                id
                    firstName
                    lastName
                    userName
                    email
                    profileImgUrl
            }
            parent{
                id
                comment
                mediaArray
                user{
                    id
                    firstName
                    lastName
                    userName
                    email
                    profileImgUrl
                }
            }
          
        }

    }
}
    `);
